### PR TITLE
feat: add date preset step

### PR DESCRIPTION
**Pull request by chielwester**

### CODE REVIEW

**Comment by RobD-tech** [comment]
We also have an action function that calculates the "now" date time value. Shouldn't we combine these two functions so that the user can choose for the values "now", "today" or "next week"? This also prevents us from having an unnecessary large number of action functions.

**Comment by chrisobdam** [comment]
Anything happening here?

**Comment by justin-betty** [comment]
Can you please add tests?

**Comment by RobD-tech** [comment]
@justin-betty What kind of tests should we (at least) add to action steps? Is there a template or a list of tests that we have to implement?

**Comment by justin-betty** [comment]
For example you can test when a certain preset is given if the expected output is correct and in the correct format. There is no template for tests, so for now unit tests are enough. you can check the native set for examples

**Pull request closed without merging**
